### ISSUE TITLE
Application exits when it fails to interact with the clipboard

### ISSUE THREAD

**Issue by alexbakker** [Granddave/aegis-rs#1]
Would it be possible to make the application fall back to not using the clipboard if it fails to interact with it? I encountered the following error when pressing enter on an entry to display its code.

```
Error: 
   0: Unknown error while interacting with the clipboard: failed to lookup address information: Temporary failure in name resolution

Location:
   src/bin/cli.rs:71

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
```

I'm using aegis-rs on NixOS, inside a fairly strict bubblewrap sandbox where there's no networking available (including unix sockets):

```sh
bwrap \
  --ro-bind /nix/store /nix/store \
  --ro-bind /path/to/vault.json /path/to/vault.json \
  --unshare-all \
  --die-with-parent \
  $(realpath $(which aegis-rs)) \
  /path/to/vault.json
```

**Comment by Granddave** [comment]
Hi, thanks for reporting the issue.

I agree that it shouldn't crash if the clipboard cannot initialize.
Fix is in master :)
