### ISSUE TITLE
Support for database version 3

### ISSUE THREAD

**Issue by opkorpela** [Granddave/aegis-rs#11]
When I try to run aegis-rs with a new export or backup, I get the following error message:

Error: 
   0: Unsupported database version: 3

Location:
   src/vault.rs:53

**Comment by Granddave** [comment]
Hi @opkorpela! What version are you running? You can check by running `aegis-rs --version`.

This issue is fixed in 0.3.1, so if you have an older version, please update and check again.
Thanks

**Comment by opkorpela** [comment]
Thank you! It works now.
