### ISSUE TITLE
Howto compile on Debian 12?

### ISSUE THREAD

**Issue by sseide** [Granddave/aegis-rs#6]
Hello, i try to install this tool on a Debian 12 system but fail on dependency resolution.

Debian bookworm (stable) provides "rustc" at version 1.63, no newer version available in updates/backports.
But it seems it is not possible to compile your app with this setup. Running "cargo install ..." as given on the Readme returns the following error:
```
error: failed to compile `aegis-rs v0.3.0 (https://github.com/Granddave/aegis-rs?tag=latest#5b1c7669)`, intermediate artifacts can be found at `/tmp/cargo-installnyX1PT`

Caused by:
  package `nix v0.27.1` cannot be built because it requires rustc 1.65 or newer, while the currently active rustc version is 1.63.0
  Either upgrade to rustc 1.65 or newer, or use
  cargo update -p nix@0.27.1 --precise ver
  where `ver` is the latest version of `nix` supporting rustc 1.63.0
```

As i am completly new to Rust i am stuck here as i have no idea on how to downgrade or check what compiler version is needed and so on...

Another question - is there some pre-compiled version available to not have the hassle with build problems due to different setups/compilers/...?

Thanks in advance for help,
S. Seide

**Comment by Granddave** [comment]
Hi @sseide, thanks for checking out the project!

I'm assuming you've installed rustc via the systems package manager? I would instead recommend installing the Rust dev environment with [Rustup](https://www.rust-lang.org/learn/get-started). That way you get a more up to date compiler and some other useful devtools. 

Regarding precompiled binaries; I haven't gotten around to set that up, but it would definitely be a good addition to the project. I'll let you know when it's added.

Let me know if you have any other questions :)

**Comment by sseide** [comment]
Hi, many thanks for the help. The current rustup setup is broken but there exists a ticket with workaround as i found out. So now its up and running. Its good to have the Token generator on mobile and pc too in sync...

Thanks for the project.
