### ISSUE TITLE
Wishlist - add key to go back from OTP to list

### ISSUE THREAD

**Issue by sseide** [Granddave/aegis-rs#7]
Hello,
thanks for this helpful program. For me it would be helpful to have the possibility to go back from displaying the OTP to the list to select a new account / token.

Current implementation (as i understand) is just a one-shot: start app -> enter password -> select one account -> exit

Here (for being lazy and not wanting to enter my password again and again but being too paranoid to store it on disc / inside env-var) it would be helpful to be able to go back from the OTP to the account list by pressing ESC / arrow left / Q or similar. Now i could select another account and display the OTP there too without having to enter my password again.

Thanks,
Stefan

**Comment by sseide** [comment]
and i do not know - maybe this could be added as an example wrapper around aegis for easier startup? Feel free to use or ignore

aegis.sh
```
#!/usr/bin/env bash
set +x

# directory with aegis backup files
STORE_DIR=~/dir/to/aegis/backups/

# try to locate authenticator binary
AUTHENTICATOR=$(command -v aegis-rs)
if [ -z "$AUTHENTICATIOR" ]; then
        if [ -f "$HOME/.cargo/bin/aegis-rs" ]; then
                AUTHENTICATOR="$HOME/.cargo/bin/aegis-rs"
        elif [ -f "$HOME/.local/cargo/bin/aegis-rs" ]; then
                AUTHENTICATOR="$HOME/.local/cargo/bin/aegis-rs"
        fi
fi
if [ -z "$AUTHENTICATOR" ]; then
        echo "aegis-rs command not found - exit"
        exit 1
fi

cd $STORE_DIR || exit 1

# sort asc, tail last (newest) filename only
KEYSTORE=$(ls aegis* | sort | tail -1)

$AUTHENTICATOR "$STORE_DIR/$KEYSTORE"
```

**Comment by Granddave** [comment]
Hello @sseide, yes, that would indeed be a nice feature to have. You are correct in your assumption that the application flow is very basic and easy since it's only running on one thread. The downside to this simplicity is that we cannot listen to keyboard input while updating the OTP code on the screen.

I've been thinking about revamping the UI to use a TUI framework instead of handing the IO ourselves to allow us to do things like you are suggesting. I don't have any time estimate or anything, but I think it's a step in the right direction.

**Comment by sseide** [comment]
Ok, thanks for the information. And no hurry. Looking forward to see it at some point in the future but current implementation works well too.

**Comment by pepa65** [comment]
Why would you not be able to listen to keyboard input while updating the OTP code on the screen?

**Comment by Granddave** [comment]
@pepa65 I mean, we _could_, but my vision is to create a lean UI with [ratatui](https://github.com/ratatui-org/ratatui) that would allow us to do some nice filtering, navigation, grouping etc.

I've been busy with personal stuff so haven't had time to work on it, but if anyone has a solution for this current issue in the meantime I'm happy to take PR's :)

**Comment by pepa65** [comment]
Going back after viewing a TOTP is the most basic navigation that would improve usability. I personally would never use grouping (and I have 85 entries). The filtering is nice. Of course, prioritize personal stuff..!

**Comment by sseide** [comment]
Using it for some time now and its working very well. As @pepa65 wrote - filtering (as it is now implemented) let me find the account very fast, its a "must have". And i would not use grouping here too, its different than mobile phone - here we have a real keyboard and already typing to start the app, Contrary to smart phone where grouping helps to go to the account needed...

Only thing needed is navigating back to the list. But as written, no hurry here.

**Comment by Granddave** [comment]
@pepa65 @sseide, I've hacked together a possible solution now with a smaller modification. Are any one of you able to check it out and run it before it gets merged possibly? :)

Gotta say, it feels good to be able to go back to the entry selection again, good suggestion!

**Comment by sseide** [comment]
sure - i'll test it tomorrow... `feature/back-to-list`?

**Comment by pepa65** [comment]
Thanks, works great!!
Not sure how difficult this would be, but it would be nice if Esc can also exit the app at the end (instead of Ctrl-C).

**Comment by Granddave** [comment]
Great, thanks!
Do you mean during the entry selection?

**Comment by pepa65** [comment]
Right, the first state after authentication, and where you end up after q/Esc in the TOTP display.

**Comment by sseide** [comment]
going back with ESC works fine (at least within the program)

But some other bugs i have found. Not sure if it is connected to current rework:

* Crtl-C while TOTP is displayed: after exit of aegis-rs normal terminal is not usable anymore. Chars typed into bash will not be displayed, cannot see what i am typing. But the characters are entered. Example: at the shell prompt "$ "  i input "ls". I cannot see the command but pressing "[enter]" i get the file listing.
And starting aegis within this terminal again i get asked for the Aegis Password but cannot input it. It seems Aegis is not accepting "[enter]" anymore. i do not get past the prompt to input my password and have to "killall aegis-rs" to get my shell back. But its not working anymore due to suppressed output...

* Crtl-C while in account list view: Exit and bash usable afterwards but "IOError":
   ```
        0: IO error: read interrupted
        1: read interrupted

  Location:
     src/main.rs:193

  Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
  Run with RUST_BACKTRACE=full to include source snippets.
  ```
  But running with env var RUST_BACKTRACE=1 or "full" does not show anything?!

**Comment by Granddave** [comment]
Thanks for the testing.

@sseide 
> But some other bugs i have found. Not sure if it is connected to current rework

Yes, these ctrl+c bugs are introduced (i think) in that commit. The current trap function doesn't seem to work in this multi threaded context. Would indeed be nice to fix that before merge, as noted in the commit message as well.

@pepa65 
> it would be nice if Esc can also exit the app at the end

> the first state after authentication

Agree, that would be a nice addition :)

**Comment by pepa65** [comment]
> * after exit of aegis-rs normal terminal is not usable anymore

Care must be taken to issue a terminal reset before exiting.

> Crtl-C while in account list view: Exit and bash usable afterwards but "IOError"

I got this sometimes, I think because of stuff in the input buffer..?
