### ISSUE TITLE
Unsupported database

### ISSUE THREAD

**Issue by ntnguyen1234** [Granddave/aegis-rs#9]
Hi, I'm using Aegis latest version and I have exported encrypted json backup with it. 

When I run `aegis-rs encrypted.json` and type my password after `Insert Aegis Password`, it says `Failed to open vault: Unsupported database version: 3`. I'm using Windows 10.

Is it an issue on windows only?

**Comment by Granddave** [comment]
Hi @ntnguyen1234! Thanks for reporting the issue.

The exported file from the Aegis App has two sets of versions in it, first the _vault version_ which is used for encryption/decryption and secondly the _database version_ which holds the actual user data. When I wrote the parser I only had a database with version 2 available, but after inspection of a database with version 3 it seems like we can continue to use the same parser. We will just miss out on groups which we don't support at the moment either way.

I have in the PR mentioned above changed the hard requirement to version 3. :)

**Comment by Granddave** [comment]
@ntnguyen1234, try the new release and see if that solves the problem for you.

**Comment by ntnguyen1234** [comment]
Hi @Granddave It works correctly now. Thanks for solving the issue :)
